# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rebble' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rebble
  pod 'Bluejay', '>= 0.1'
  pod 'BulletinBoard'

  target 'RebbleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RebbleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
